name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Debug - List directory contents
        run: |
          echo "Current directory contents:"
          ls -la

      - name: Create config.js
        run: |
          echo "Creating config.js..."
          cat > config.js << EOL
          const CONFIG = {
            apiKey: '${{ secrets.GOOGLE_API_KEY }}',
            clientId: '${{ secrets.GOOGLE_CLIENT_ID }}',
            spreadsheetId: '${{ secrets.GOOGLE_SPREADSHEET_ID }}',
            sheetName: 'ErrorReports'
          };
          EOL
          echo "config.js created"

      - name: Verify config.js
        run: |
          echo "Verifying config.js..."
          if [ ! -f config.js ]; then
            echo "ERROR: config.js was not created"
            exit 1
          fi
          if ! grep -q "const CONFIG" config.js; then
            echo "ERROR: config.js is not properly formatted"
            exit 1
          fi
          echo "config.js verification passed"
          echo "config.js contents (without sensitive data):"
          sed 's/apiKey:.*,/apiKey: "***",/' config.js | sed 's/clientId:.*,/clientId: "***",/'

      - name: Debug - List files before deployment
        run: |
          echo "Files to be deployed:"
          ls -la

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"
          force_orphan: true 