name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Create config.js
        run: |
          cat > config.js << EOL
          const CONFIG = {
            apiKey: '${{ secrets.GOOGLE_API_KEY }}',
            clientId: '${{ secrets.GOOGLE_CLIENT_ID }}',
            spreadsheetId: '${{ secrets.GOOGLE_SPREADSHEET_ID }}',
            sheetName: 'ErrorReports'
          };
          EOL

      - name: Verify config.js
        run: |
          if [ ! -f config.js ]; then
            echo "config.js was not created"
            exit 1
          fi
          if ! grep -q "const CONFIG" config.js; then
            echo "config.js is not properly formatted"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          commit_message: "Deploy: ${{ github.event.head_commit.message }}" 