name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Debug - Check secrets
        run: |
          echo "Checking if secrets are set..."
          if [ -n "${{ secrets.GOOGLE_API_KEY }}" ]; then
            echo "✅ GOOGLE_API_KEY is set"
            echo "API Key length: ${#GOOGLE_API_KEY}"
            echo "API Key starts with AIza: ${{ startsWith(secrets.GOOGLE_API_KEY, 'AIza') }}"
          else
            echo "❌ GOOGLE_API_KEY is not set"
          fi
          if [ -n "${{ secrets.GOOGLE_CLIENT_ID }}" ]; then
            echo "✅ GOOGLE_CLIENT_ID is set"
          else
            echo "❌ GOOGLE_CLIENT_ID is not set"
          fi
          if [ -n "${{ secrets.GOOGLE_SPREADSHEET_ID }}" ]; then
            echo "✅ GOOGLE_SPREADSHEET_ID is set"
          else
            echo "❌ GOOGLE_SPREADSHEET_ID is not set"
          fi

      - name: Replace environment variables
        run: |
          # Create a temporary file
          cp index.html index.html.tmp
          
          # Debug - Show original content
          echo "Original content:"
          grep -A 5 "const CONFIG" index.html.tmp
          
          # Replace environment variables
          sed -i "s/{{ GOOGLE_API_KEY }}/${{secrets.GOOGLE_API_KEY}}/g" index.html.tmp
          sed -i "s/{{ GOOGLE_CLIENT_ID }}/${{secrets.GOOGLE_CLIENT_ID}}/g" index.html.tmp
          sed -i "s/{{ GOOGLE_SPREADSHEET_ID }}/${{secrets.GOOGLE_SPREADSHEET_ID}}/g" index.html.tmp
          
          # Debug - Show replaced content (without showing actual values)
          echo "Replaced content:"
          grep -A 5 "const CONFIG" index.html.tmp | sed 's/apiKey:.*,/apiKey: "***",/' | sed 's/clientId:.*,/clientId: "***",/'
          
          # Verify replacements
          if grep -q "${{secrets.GOOGLE_API_KEY}}" index.html.tmp; then
            echo "✅ API key was replaced"
          else
            echo "❌ API key was not replaced"
            echo "Current content:"
            grep -A 5 "const CONFIG" index.html.tmp
          fi
          
          # Move the temporary file back
          mv index.html.tmp index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: .
          publish_branch: gh-pages
          commit_message: "Deploy: ${{github.event.head_commit.message}}"
          force_orphan: true 