name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Replace environment variables
        run: |
          # Create a temporary file
          cp index.html index.html.tmp
          
          # Replace environment variables
          sed -i "s/{{ GOOGLE_API_KEY }}/${{ secrets.GOOGLE_API_KEY }}/g" index.html.tmp
          sed -i "s/{{ GOOGLE_CLIENT_ID }}/${{ secrets.GOOGLE_CLIENT_ID }}/g" index.html.tmp
          sed -i "s/{{ GOOGLE_SPREADSHEET_ID }}/${{ secrets.GOOGLE_SPREADSHEET_ID }}/g" index.html.tmp
          
          # Verify replacements (without showing actual values)
          echo "Environment variables replaced in index.html"
          grep -q "apiKey:" index.html.tmp && echo "✅ API key placeholder found"
          grep -q "clientId:" index.html.tmp && echo "✅ Client ID placeholder found"
          grep -q "spreadsheetId:" index.html.tmp && echo "✅ Spreadsheet ID placeholder found"
          
          # Move the temporary file back
          mv index.html.tmp index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"
          force_orphan: true 